sudo: false

services: 
  - postgresql

language: node_js
node_js:
  - "8"

addons: 
   postgresql: "10"

env: 
  global: 
    - NODE_ENV=development
    - SECRETKEY="fadees"
    - PGHOST=localhost
    - PGURL=postgresql://fiston:0788475785@localhost/sendIT
    - PGUSER=fiston
    - PGDATABASE=sendIT
    - PGPASSWORD=0788475785
    - PGPORT=5432
before_script:
    - psql -c 'create database sendIT;' -U postgres
    - psql -c "CREATE USER fiston WITH PASSWORD '0788475785';" -U postgres

script:
   - npm test

after_success:
   npm run coverage   
         